// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test_Project.Data;

namespace testProject.Migrations
{
    [DbContext(typeof(test_ProjectDbContext))]
    [Migration("20190211205604_Conferences")]
    partial class Conferences
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("test_Project.Data.Models.BlogsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<bool?>("Deleted");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image")
                        .HasMaxLength(50);

                    b.Property<bool>("IsFeatured");

                    b.Property<string>("Keywords")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("Message");

                    b.Property<byte[]>("Timestamp");

                    b.Property<string>("Title")
                        .HasMaxLength(150);

                    b.Property<Guid?>("UserGuid");

                    b.Property<int?>("VideoID");

                    b.HasKey("Id");

                    b.HasIndex("VideoID");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("test_Project.Data.Models.NewsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<bool?>("Deleted");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image")
                        .HasMaxLength(50);

                    b.Property<bool>("IsFeatured");

                    b.Property<string>("Keywords")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("Source")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Timestamp");

                    b.Property<string>("Title")
                        .HasMaxLength(150);

                    b.Property<Guid?>("UserGuid");

                    b.Property<int?>("VideoID");

                    b.HasKey("Id");

                    b.HasIndex("VideoID");

                    b.ToTable("News");
                });

            modelBuilder.Entity("test_Project.Data.Models.VideosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DateCreated");

                    b.Property<bool?>("Deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<bool>("Gallery");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsFeatured");

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("Site")
                        .HasMaxLength(50);

                    b.Property<byte[]>("Timestamp");

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.Property<Guid?>("UserGuid");

                    b.Property<int?>("Views");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("test_Project.Data.Models.WebcastsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alert")
                        .HasMaxLength(150);

                    b.Property<string>("Body");

                    b.Property<string>("Contributors")
                        .HasMaxLength(500);

                    b.Property<DateTime>("Date");

                    b.Property<DateTime?>("DateCreated");

                    b.Property<bool?>("Deleted");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<bool>("IsFeatured");

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("MediaFile")
                        .HasMaxLength(150);

                    b.Property<string>("Subtitle")
                        .HasMaxLength(150);

                    b.Property<byte[]>("Timestamp");

                    b.Property<string>("Title")
                        .HasMaxLength(150);

                    b.Property<Guid?>("UserGuid");

                    b.HasKey("Id");

                    b.ToTable("Webcasts");
                });

            modelBuilder.Entity("test_Project.Data.Models.ZipCodesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasMaxLength(75);

                    b.Property<DateTime?>("DateCreated");

                    b.Property<bool?>("Deleted");

                    b.Property<Guid?>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("State")
                        .HasMaxLength(2);

                    b.Property<byte[]>("Timestamp");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("ZipCodes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("test_Project.Data.Models.BlogsModel", b =>
                {
                    b.HasOne("test_Project.Data.Models.VideosModel", "Video")
                        .WithMany()
                        .HasForeignKey("VideoID");
                });

            modelBuilder.Entity("test_Project.Data.Models.NewsModel", b =>
                {
                    b.HasOne("test_Project.Data.Models.VideosModel", "Video")
                        .WithMany()
                        .HasForeignKey("VideoID");
                });
#pragma warning restore 612, 618
        }
    }
}
